version: '3.8'
services:
  msger:
    env_file:
      - .env.local
    image: msger-dev
    build:
      dockerfile: Dockerfile.dev
    container_name: msger_c
    ports:
      - '3000:3000'
    volumes:
      - ./src:/msger/src
      - ./public:/msger/public
      - /msger/node_modules